python simple_categories.py /Users/argy/workspace/childes_parse/data/PARSED_spacy/PARSED/age_0_12.parsed /Users/argy/workspace/childes_parse/data/stats/age_0_12_categories.txt
python simple_categories.py /Users/argy/workspace/childes_parse/data/PARSED_spacy/PARSED/age_12_24.parsed /Users/argy/workspace/childes_parse/data/stats/age_12_24_categories.txt
python simple_categories.py /Users/argy/workspace/childes_parse/data/PARSED_spacy/PARSED/age_24_36.parsed /Users/argy/workspace/childes_parse/data/stats/age_24_36_categories.txt
python simple_categories.py /Users/argy/workspace/childes_parse/data/PARSED_spacy/PARSED/age_36_48.parsed /Users/argy/workspace/childes_parse/data/stats/age_36_48_categories.txt
python simple_categories.py /Users/argy/workspace/childes_parse/data/PARSED_spacy/PARSED/age_48_60.parsed /Users/argy/workspace/childes_parse/data/stats/age_48_60_categories.txt
python simple_categories.py /Users/argy/workspace/childes_parse/data/PARSED_spacy/PARSED/age_60_72.parsed /Users/argy/workspace/childes_parse/data/stats/age_60_72_categories.txt
python simple_categories.py /Users/argy/workspace/childes_parse/data/PARSED_spacy/PARSED/age_72_84.parsed /Users/argy/workspace/childes_parse/data/stats/age_72_84_categories.txt
python simple_categories.py /Users/argy/workspace/childes_parse/data/PARSED_spacy/PARSED/age_84_96.parsed /Users/argy/workspace/childes_parse/data/stats/age_84_96_categories.txt
python simple_categories.py /Users/argy/workspace/childes_parse/data/PARSED_spacy/PARSED/age_96_108.parsed /Users/argy/workspace/childes_parse/data/stats/age_96_108_categories.txt
python simple_categories.py /Users/argy/workspace/childes_parse/data/PARSED_spacy/PARSED/age_108_120.parsed /Users/argy/workspace/childes_parse/data/stats/age_108_120_categories.txt
python simple_categories.py /Users/argy/workspace/childes_parse/data/PARSED_spacy/PARSED/age_120_192.parsed /Users/argy/workspace/childes_parse/data/stats/age_120_192_categories.txt

python pos_adv_categories.py /Users/argy/workspace/childes_parse/data/PARSED_spacy/PARSED/age_12_24.parsed /Users/argy/workspace/childes_parse/data/stats/age_12_24_pos_adv_categories.txt
python pos_adv_categories.py /Users/argy/workspace/childes_parse/data/PARSED_spacy/PARSED/age_24_36.parsed /Users/argy/workspace/childes_parse/data/stats/age_24_36_pos_adv_categories.txt
python pos_adv_categories.py /Users/argy/workspace/childes_parse/data/PARSED_spacy/PARSED/age_36_48.parsed /Users/argy/workspace/childes_parse/data/stats/age_36_48_pos_adv_categories.txt
python pos_adv_categories.py /Users/argy/workspace/childes_parse/data/PARSED_spacy/PARSED/age_48_60.parsed /Users/argy/workspace/childes_parse/data/stats/age_48_60_pos_adv_categories.txt
python pos_adv_categories.py /Users/argy/workspace/childes_parse/data/PARSED_spacy/PARSED/age_60_72.parsed /Users/argy/workspace/childes_parse/data/stats/age_60_72_pos_adv_categories.txt
python pos_adv_categories.py /Users/argy/workspace/childes_parse/data/PARSED_spacy/PARSED/age_72_84.parsed /Users/argy/workspace/childes_parse/data/stats/age_72_84_pos_adv_categories.txt
python pos_adv_categories.py /Users/argy/workspace/childes_parse/data/PARSED_spacy/PARSED/age_84_96.parsed /Users/argy/workspace/childes_parse/data/stats/age_84_96_pos_adv_categories.txt
python pos_adv_categories.py /Users/argy/workspace/childes_parse/data/PARSED_spacy/PARSED/age_96_108.parsed /Users/argy/workspace/childes_parse/data/stats/age_96_108_pos_adv_categories.txt
python pos_adv_categories.py /Users/argy/workspace/childes_parse/data/PARSED_spacy/PARSED/age_108_120.parsed /Users/argy/workspace/childes_parse/data/stats/age_108_120_pos_adv_categories.txt
python pos_adv_categories.py /Users/argy/workspace/childes_parse/data/PARSED_spacy/PARSED/age_120_192.parsed /Users/argy/workspace/childes_parse/data/stats/age_120_192_pos_adv_categories.txt

python negated.py /Users/argy/workspace/childes_parse/data/PARSED_spacy/PARSED/age_0_12.parsed /Users/argy/workspace/childes_parse/data/stats/age_0_12_negated.txt
python negated.py /Users/argy/workspace/childes_parse/data/PARSED_spacy/PARSED/age_12_24.parsed /Users/argy/workspace/childes_parse/data/stats/age_12_24_negated.txt
python negated.py /Users/argy/workspace/childes_parse/data/PARSED_spacy/PARSED/age_24_36.parsed /Users/argy/workspace/childes_parse/data/stats/age_24_36_negated.txt
python negated.py /Users/argy/workspace/childes_parse/data/PARSED_spacy/PARSED/age_36_48.parsed /Users/argy/workspace/childes_parse/data/stats/age_36_48_negated.txt
python negated.py /Users/argy/workspace/childes_parse/data/PARSED_spacy/PARSED/age_48_60.parsed /Users/argy/workspace/childes_parse/data/stats/age_48_60_negated.txt
python negated.py /Users/argy/workspace/childes_parse/data/PARSED_spacy/PARSED/age_60_72.parsed /Users/argy/workspace/childes_parse/data/stats/age_60_72_negated.txt
python negated.py /Users/argy/workspace/childes_parse/data/PARSED_spacy/PARSED/age_72_84.parsed /Users/argy/workspace/childes_parse/data/stats/age_72_84_negated.txt
python negated.py /Users/argy/workspace/childes_parse/data/PARSED_spacy/PARSED/age_84_96.parsed /Users/argy/workspace/childes_parse/data/stats/age_84_96_negated.txt
python negated.py /Users/argy/workspace/childes_parse/data/PARSED_spacy/PARSED/age_96_108.parsed /Users/argy/workspace/childes_parse/data/stats/age_96_108_negated.txt
python negated.py /Users/argy/workspace/childes_parse/data/PARSED_spacy/PARSED/age_108_120.parsed /Users/argy/workspace/childes_parse/data/stats/age_108_120_negated.txt
python negated.py /Users/argy/workspace/childes_parse/data/PARSED_spacy/PARSED/age_120_192.parsed /Users/argy/workspace/childes_parse/data/stats/age_120_192_negated.txt

python questions.py /Users/argy/workspace/childes_parse/data/PARSED_spacy/PARSED/age_0_12.parsed /Users/argy/workspace/childes_parse/data/stats/age_0_12_questions.txt
python questions.py /Users/argy/workspace/childes_parse/data/PARSED_spacy/PARSED/age_12_24.parsed /Users/argy/workspace/childes_parse/data/stats/age_12_24_questions.txt
python questions.py /Users/argy/workspace/childes_parse/data/PARSED_spacy/PARSED/age_24_36.parsed /Users/argy/workspace/childes_parse/data/stats/age_24_36_questions.txt
python questions.py /Users/argy/workspace/childes_parse/data/PARSED_spacy/PARSED/age_36_48.parsed /Users/argy/workspace/childes_parse/data/stats/age_36_48_questions.txt
python questions.py /Users/argy/workspace/childes_parse/data/PARSED_spacy/PARSED/age_48_60.parsed /Users/argy/workspace/childes_parse/data/stats/age_48_60_questions.txt
python questions.py /Users/argy/workspace/childes_parse/data/PARSED_spacy/PARSED/age_60_72.parsed /Users/argy/workspace/childes_parse/data/stats/age_60_72_questions.txt
python questions.py /Users/argy/workspace/childes_parse/data/PARSED_spacy/PARSED/age_72_84.parsed /Users/argy/workspace/childes_parse/data/stats/age_72_84_questions.txt
python questions.py /Users/argy/workspace/childes_parse/data/PARSED_spacy/PARSED/age_84_96.parsed /Users/argy/workspace/childes_parse/data/stats/age_84_96_questions.txt
python questions.py /Users/argy/workspace/childes_parse/data/PARSED_spacy/PARSED/age_96_108.parsed /Users/argy/workspace/childes_parse/data/stats/age_96_108_questions.txt
python questions.py /Users/argy/workspace/childes_parse/data/PARSED_spacy/PARSED/age_108_120.parsed /Users/argy/workspace/childes_parse/data/stats/age_108_120_questions.txt
python questions.py /Users/argy/workspace/childes_parse/data/PARSED_spacy/PARSED/age_120_192.parsed /Users/argy/workspace/childes_parse/data/stats/age_120_192_questions.txt
